// taskea-docs/sidebars.js
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Este ID 'tutorialSidebar' deve corresponder ao sidebarId usado no docusaurus.config.js
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro', // Aponta para o ficheiro docs/intro.md
    },
    {
      type: 'category',
      label: 'Back-end (Node.js)',
      link: {
        type: 'doc',
        // ID baseado no caminho: docs/backend/DocumentacaoTecnicadoBackend-ProjetoTaskea.md
        id: 'backend/DocumentacaoTecnicadoBackend-ProjetoTaskea',
      },
      items: [
        // Se quiseres que o mesmo item apareça abaixo da categoria ao expandir, repete o ID:
        // 'backend/DocumentacaoTecnicadoBackend-ProjetoTaskea',
        // Ou, se planeias ter mais ficheiros nesta pasta no futuro e queres que apareçam:
        // { type: 'autogenerated', dirName: 'backend' }, 
      ],
    },
    {
      type: 'category',
      label: 'Banco de Dados (SQLite)',
      link: {
        type: 'doc',
        // ID baseado no caminho: docs/database/DocumentacaoTecnicadoBancodeDados-Projeto Taskea.md
        // Docusaurus provavelmente criará um slug como 'DocumentacaoTecnicadoBancodeDados-Projeto-Taskea'
        // É mais seguro usar nomes de ficheiro sem espaços.
        id: 'database/DocumentacaoTecnicadoBancodeDados-Projeto Taskea', 
      },
      items: [],
    },
    {
      type: 'category',
      label: 'Front-end (CSS)',
      link: {
        type: 'doc',
        // ID baseado no caminho: docs/frontend/estilizacao.md
        id: 'frontend/estilizacao',
      },
      items: [],
    },
  ],
};

module.exports = sidebars;